yarnPath: .yarn/releases/yarn-4.1.1.cjs
nodeLinker: node-modules


npmScopes:
  mjpowersjr:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN}
    npmRegistryServer: https://npm.pkg.github.com
